### ISSUE TITLE
Getter for equation variables

### ISSUE THREAD

**Issue by bwrsandman** [glenfletcher/Equation#10]
It would be nice to be able to get a list of variables from an expression.
## Use case:

Application has a bank of values stored and other than I can fetch or compute.
User input an expression
Application uses variable name getter and fetches values for these variables.
Application calls expression with values and returns result to user.

It is important that the application doesn't have to fetch all possible values for each expression.

**Comment by glenfletcher** [comment]
Yes I've been meaning to add a variable iterator i.e.

``` .py
fn = Expression(expr,expect_vars)
for v in fn:
    if v in expect_vars:
        continue
    fn[v] = fetch(v)
fn(*args) # args is the list of required arguments i.e. time, position, may be empty should match expect vars
```

Any other suggestions towards this feature would be appericated

**Comment by bwrsandman** [comment]
I did a quick hack earlier this weekend.
It involved a `filter()` and a `map()` call to your tokens.
I filtered `type is Variable` and mapped `lambda x: x.name` and returned it as a list.

That may not be the way you want to go about it, which is why I didn't submit a PR.

**Comment by glenfletcher** [comment]
__argsused is a set of every variable that is seen in the equation
__args is a list of position mapping, argorder, folloed by every other variable left to right in the equation.

i.e.

``` .py
>>> fn = Expression("a*e^(k*t)",["t"])
>>> fn._Expression__argsused
set(['a', 'k', 'e', 't'])
>>> fn._Expression__args
['t', 'a', 'e', 'k', 't'] # this shouldn't have the second t, only just found this bug
```

I've just added the iterator

``` .py
def __iter__(self):
        return iter(self.__argsused)
```

``` .py
>>> from Equation import Expression
>>> fn = Expression("a*e^(k*t)",["t"])
>>> for v in fn:
...    print v
... 
a
k
e
t
```
