### ISSUE TITLE
Operation precedence is wrong

### ISSUE THREAD

**Issue by bwrsandman** [glenfletcher/Equation#11]
Currently, addition and substraction have the same precedence with binary operators and comparison operators.

I propose having this level of precedence
1. Unary
2. Abs
3. Mod
4. Addition, substraction
5. Or and And
6. Comparison

It would be important to also add unittests for non-trivial equations which would have different results with different precedence.

**Comment by glenfletcher** [comment]
Is that that the lower number operators will be applied first? or the Higher number.

I've only just added the comparison ops, so I will need to adjust this

**Comment by bwrsandman** [comment]
Lower numbers have higher precedence (Run before greater numbers).
i.e. Additions before And, Ors before Comparisons.

Also, in my comment, comparisons relate to: `==`, `!=`, `>=`, `>`, `<`, `<=` and are in my PR #9

**Comment by glenfletcher** [comment]
Ok that the opside of How I implemented it

``` .py
>>> fn = Expression("a{2}b{1}c{2}d")
>>> fn.show()
<Equation.core.ExpressionVariable(a) object at 0x04509d70>
<Equation.core.ExpressionVariable(b) object at 0x04509e30>
<Equation.core.ExpressionFunction({2},2) object at 0x04509e50>
<Equation.core.ExpressionVariable(c) object at 0x045096f0>
<Equation.core.ExpressionVariable(d) object at 0x04521690>
<Equation.core.ExpressionFunction({2},2) object at 0x045216b0>
<Equation.core.ExpressionFunction({1},2) object at 0x045216d0>
```

The Precedence is in the {} i.e. `a b {2} c d {2} {1}` -> `((a {2} b) {1} (c {2} d))`

see http://en.wikipedia.org/wiki/Reverse_Polish_notation
This is used internally

Show is the lower numbers first a standard? show I change my implimication?

**Comment by bwrsandman** [comment]
Interesting.
Are you saying that in your implementation, a higher number for precedence will be evaluated first?

If that's the case, I have to fix #9, comparison operations should be last.

I wouldn't say one way is better than the other, you just have to keep in mind that you'll be adding operations with different precedence. If you're more likely to add a level of precedence with high precedence, you want a higher number to indicate high precedence to avoid incrementing the precedence of other operators ( _with 1, 2, 3, 4, add 5_ vs _with 1, 2, 3, 4, increment all by one and add 1_). The converse is true if you're more likely to add lower precedence level.
The important thing is to document it clearly in the code and in your docs, if you have already, I might have skipped it.

Fyi, I was going by python's own precedence.

**Comment by glenfletcher** [comment]
It will work with zero and negative precedence as well, so it doesn't really matter

``` .py
.....
                while True:
                    if (fn['prec'] <= fs['prec']):
                        self.__expr.append(ExpressionFunction(fs['func'],fs['args'],fs['str'],fs['latex'],op[0],False))
 ....
```

However matching that I python is a good idea and I just need to change the condition.

Commited change

**Comment by bwrsandman** [comment]
LGTM! :thumbsup:
