### ISSUE TITLE
Remove Print calls

### ISSUE THREAD

**Issue by bwrsandman** [glenfletcher/Equation#12]
The library should not be printing.
I get the following everytime I create an expression and it scales relative to the complexity of the equation.

``` python
()
()
```

If absolutely necessary, the logging module should be used, but I think it's better if this library just doesn't output to the console.

**Comment by glenfletcher** [comment]
Are you working off the release code? i.e. v1.0, it shouldn't be printing some of the commits will print as they have debugging print statements in them

**Comment by bwrsandman** [comment]
I am working off of the git upstream, as I am adding features and fixing code for my own uses.

**Comment by glenfletcher** [comment]
The I'll assume its just some of the temporary debugging code.

**Comment by bwrsandman** [comment]
Yes, the `()` seem to be gone, thank you.

Looking at the rest of the code, there still are some print calls:
https://github.com/alphaomega-technology/Equation/blob/ea609772d171f63b13d78cfb720d715e18cf2dd7/Equation/core.py

I don't use this function, but I assume anyone using the library might want this returned as a list of strings instead of copy-pasting it from the console.
