### ISSUE TITLE
Support for Hexadecimal and Octal numbers

### ISSUE THREAD

**Issue by bwrsandman** [glenfletcher/Equation#14]
I would like to be able to write equations using hexadecimal and octal notation:

``` python
hex_int = 0xD1FF
octal_int = 0o123
```

The following usecase in the form of a unittest:

``` python
class TestHexEquation(unittest.TestCase):
    def setUp(self):
        self.fn = Expression("x == 0x1A")

    def testCall(self):
        self.assertTrue(self.fn(26))
        self.assertTrue(self.fn(0o32))
        self.assertTrue(self.fn(0x1A))
        self.assertFalse(self.fn(10))
        self.assertFalse(self.fn(0x26))
        self.assertFalse(self.fn(0o10))
        self.assertFalse(self.fn(0o26))


    def testType(self):
        self.assertEqual(type(self.fn(1)), bool)
```

``` python
class TestOctEquation(unittest.TestCase):
    def setUp(self):
        self.fn = Expression("x == 0o10")

    def testCall(self):
        self.assertTrue(self.fn(8))
        self.assertTrue(self.fn(0x8))
        self.assertTrue(self.fn(0o10))
        self.assertFalse(self.fn(10))
        self.assertFalse(self.fn(0x10))


    def testType(self):
        self.assertEqual(type(self.fn(1)), bool)
```

Edge cases:
- Invalid octal numbers: `Expression("x == 0o9")`
- Upper and lower case hex: `Expression("x == 0x1a")`
- The following syntax for octal is invalid in python3: `oct_int = 0123`

**Comment by glenfletcher** [comment]
see branch **hex_oct_numbers**

Still needs to be tested

What do you think about support for other syntaxs

i.e. intel asm syntax `0FCh` or html colour code and lisp `#FC` or visual basic `&H5A3` and `0h5A3` not sure of that one but I've seen it the fore for hex and `073`, `o73`, `q73`, `@73` or `73o`

Should they be enabled by default or turned on/off with a few functions can add module Equation.base for controlling this.

**Comment by bwrsandman** [comment]
I don't think anyone will be using html colour code or intel syntax, but I could be wrong.
Python/C style numbers are universal enough. I don't think anyone will be shocked if they're the defacto numbers to use as long as it's documented somewhere.

Be careful with numbers with preceeding symbols such as `#&@` as they are often used as operators: `& == bitwise and`, `@ python matrix multiplication`

As for the tests, I hope the unitests I provided are good enough. :)

**Comment by glenfletcher** [comment]
Changes Merged to master
