### ISSUE TITLE
install issue: "ImportError: No module named ez_setup"

### ISSUE THREAD

**Issue by ifmihai** [glenfletcher/Equation#6]
I'm on mac 10.9.2
anaconda environment

i tried to install via: 
pip install -i https://pypi.binstar.org/pypi/simple Equation

(as a newbie, I'm not sure if it's needed to install packages from binstar, or not)

**Comment by glenfletcher** [comment]
Sorry, the file was missing from the package, I've updated the source package on github, and https://pypi.python.org, binstar is a minor and may take some time to update with the changes I would suggest using
`pip install Equation` for now to install directly from https://pypi.python.org
